### PR TITLE
Installed REVColorSensor lib, created Constants

### LINKED ISSUE #13: Create Constants File

### PR DESCRIPTION
**Pull request by aidund**
title

Closes #13

### CODE REVIEW

**Review by legoguy1000 — APPROVED** [review]

**Review by legoguy1000 — CHANGES_REQUESTED** [review]
Fix the formatting comments

**Comment by aidund** [comment]
@legoguy1000 even variable naming reqs?

**Comment by legoguy1000** [comment]
> @legoguy1000 even variable naming reqs?

Yes, because i'm about to have it fail when errors to enforce the standard.

**Comment by aidund** [comment]
@legoguy1000 Formatting complete.

**Review by legoguy1000 — APPROVED** [review]

**Pull request merged**
